import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiDelete, apiGet, apiPost } from "@/lib/api";
import type { ContextSearchResponse, PersonaEntry, PersonaView } from "@/lib/skipti";
import { PageSkeleton } from "@/components/PageSkeleton";

export default function Context() {
  const client = useQueryClient(); const [category, setCategory] = useState("Goals"); const [label, setLabel] = useState(""); const [value, setValue] = useState(""); const [query, setQuery] = useState("");
  const persona = useQuery({ queryKey: ["persona"], queryFn: () => apiGet<PersonaView>("/persona"), retry: false });
  const create = useMutation({ mutationFn: () => apiPost<PersonaEntry>("/persona/entries", { category, label, value, entry_type: "fact", scope: "global", sensitivity: "standard", temporary: false }), onSuccess: () => { client.invalidateQueries({ queryKey: ["persona"] }); setLabel(""); setValue(""); toast.success("Context entry approved"); }, onError: () => toast.error("Could not add context") });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete<{ message: string }>(`/persona/entries/${id}`), onSuccess: () => { client.invalidateQueries({ queryKey: ["persona"] }); toast.success("Context entry deleted"); }, onError: () => toast.error("Could not delete context") });
  const search = useMutation({ mutationFn: () => apiPost<ContextSearchResponse>("/context/search", { query, max_entries: 5 }), onError: () => toast.error("Context search failed") });
  const grouped = (persona.data?.entries ?? []).reduce<Record<string, PersonaEntry[]>>((acc, entry) => { (acc[entry.category] ??= []).push(entry); return acc; }, {});
  return <AppShell><PageHeader eyebrow="Persona core" title="Approved context, in full view." description="Base Persona facts and evolving preferences remain granular, attributable, editable, and selectively retrievable." action={<StatusPill tone="brand">Revision {persona.data?.revision ?? "—"}</StatusPill>} />
    {persona.isLoading ? <PageSkeleton cards={4} testId="context-loading-skeleton" /> : <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]" data-testid="context-main-grid"><div className="space-y-5" data-testid="context-category-list">{Object.entries(grouped).map(([group, entries]) => <article className="panel" key={group} data-testid={`context-category-${group.toLowerCase().replaceAll(" ", "-")}`}><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-heading text-3xl" data-testid={`context-category-${group.toLowerCase().replaceAll(" ", "-")}-title`}>{group}</h2><StatusPill>{entries.length} entries</StatusPill></div><div className="divide-y divide-border">{entries.map((entry) => <div className="group flex items-start gap-4 p-5" key={entry.id} data-testid={`context-entry-${entry.id}`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium" data-testid={`context-entry-${entry.id}-label`}>{entry.label}</p><StatusPill tone={entry.approval_status === "approved" ? "good" : "warning"}>{entry.approval_status}</StatusPill></div><p className="mt-2 text-xs leading-5 text-muted-foreground" data-testid={`context-entry-${entry.id}-value`}>{entry.value}</p><p className="mt-3 font-mono text-[8px] uppercase tracking-widest text-[#655d5a]" data-testid={`context-entry-${entry.id}-source`}>{entry.entry_type} · {entry.scope} · {entry.source}</p></div><Button variant="ghost" size="icon-sm" onClick={() => remove.mutate(entry.id)} aria-label={`Delete ${entry.label}`} data-testid={`context-entry-${entry.id}-delete-button`}><Trash2 className="size-3.5" /></Button></div>)}</div></article>)}</div>
      <aside className="space-y-6 xl:sticky xl:top-8 xl:self-start" data-testid="context-tools-aside"><form className="panel p-6" onSubmit={(event) => { event.preventDefault(); create.mutate(); }} data-testid="context-add-form"><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="context-add-kicker">Owner-approved addition</p><h2 className="mt-2 font-heading text-3xl" data-testid="context-add-title">Add context</h2><div className="mt-6 space-y-3"><Input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Category" required data-testid="context-category-input" /><Input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Label" required data-testid="context-label-input" /><Input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Context value" required data-testid="context-value-input" /></div><Button className="mt-4" type="submit" disabled={create.isPending} data-testid="context-add-submit-button"><Plus className="size-4" /> Add approved entry</Button></form>
      <form className="panel overflow-hidden p-6" onSubmit={(event) => { event.preventDefault(); search.mutate(); }} data-testid="context-router-form"><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="context-router-kicker">Context Router probe</p><h2 className="mt-2 font-heading text-3xl" data-testid="context-router-title">Test minimum disclosure</h2><div className="mt-6 flex gap-2"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What model fits my laptop?" required data-testid="context-router-query-input" /><Button type="submit" size="icon" disabled={search.isPending} aria-label="Search context" data-testid="context-router-search-button"><Search className="size-4" /></Button></div>{search.isPending ? <div className="mt-6 space-y-3" data-testid="context-router-loading"><div className="skeleton h-12 rounded-xl" /><div className="skeleton h-12 rounded-xl" /></div> : null}{search.data ? <div className="mt-6" data-testid="context-router-results"><div className="mb-4 grid grid-cols-3 gap-px overflow-hidden rounded-xl bg-border"><div className="bg-[#100d0e] p-3"><p className="font-heading text-2xl" data-testid="context-router-selected-count">{search.data.selected.length}</p><p className="font-mono text-[8px] uppercase text-muted-foreground">Selected</p></div><div className="bg-[#100d0e] p-3"><p className="font-heading text-2xl" data-testid="context-router-excluded-count">{search.data.excluded_count}</p><p className="font-mono text-[8px] uppercase text-muted-foreground">Excluded</p></div><div className="bg-[#100d0e] p-3"><p className="font-heading text-2xl" data-testid="context-router-token-count">~{search.data.approximate_tokens}</p><p className="font-mono text-[8px] uppercase text-muted-foreground">Tokens</p></div></div>{search.data.selected.map((item, index) => <div className="animate-trace-in border-t border-border py-3" style={{ animationDelay: `${index * 70}ms` }} key={item.id} data-testid={`context-router-result-${item.id}`}><p className="font-mono text-[9px] text-[#d7a0b1]" data-testid={`context-router-result-${item.id}-label`}>{item.category} / {item.label}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground" data-testid={`context-router-result-${item.id}-reason`}>{item.reason}</p></div>)}</div> : null}</form></aside></section>}
  </AppShell>;
}