import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Braces, Database, Layers3, Share2 } from "lucide-react";
import { Link } from "react-router-dom";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { buttonVariants } from "@/components/ui/button";
import { apiGet } from "@/lib/api";
import type { Overview } from "@/lib/skipti";
import { PageSkeleton } from "@/components/PageSkeleton";

export default function Dashboard() {
  const overview = useQuery({ queryKey: ["overview"], queryFn: () => apiGet<Overview>("/overview"), retry: false });
  const data = overview.data;
  return <AppShell>
    <PageHeader eyebrow="My Skipti" title="Context, held in one place." description="Your approved Persona and Project Holders form one canonical memory layer for every authorized AI client." action={<Link to="/playground" className={buttonVariants()} data-testid="dashboard-open-playground-link">Open playground <ArrowUpRight className="size-4" /></Link>} />
    {overview.isLoading ? <PageSkeleton cards={4} testId="dashboard-loading-skeleton" /> : <>
    {overview.isError ? <div className="panel p-8" data-testid="dashboard-auth-required"><p className="font-heading text-3xl" data-testid="dashboard-auth-title">Your session has ended.</p><Link to="/login" className="mt-5 inline-block text-sm text-[#d7a0b1] underline" data-testid="dashboard-login-link">Sign in again</Link></div> : null}
    <section className="grid gap-px overflow-hidden rounded-2xl border border-border bg-border shadow-[0_20px_50px_rgba(0,0,0,.14)] md:grid-cols-4" data-testid="dashboard-stat-grid">
      {[{ label: "Persona revision", value: data?.persona_revision ?? "—", icon: Database }, { label: "Approved entries", value: data?.persona_entries ?? "—", icon: Layers3 }, { label: "Project holders", value: data?.project_count ?? "—", icon: Braces }, { label: "Active passes", value: data?.active_shares ?? "—", icon: Share2 }].map((stat) => { const Icon = stat.icon; return <div className="bg-[#151313] p-6" key={stat.label} data-testid={`dashboard-${stat.label.toLowerCase().replaceAll(" ", "-")}-stat`}><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground" data-testid={`dashboard-${stat.label.toLowerCase().replaceAll(" ", "-")}-label`}>{stat.label}</span><Icon className="size-4 text-[#9f5169]" /></div><p className="mt-7 font-heading text-5xl font-light" data-testid={`dashboard-${stat.label.toLowerCase().replaceAll(" ", "-")}-value`}>{stat.value}</p></div>; })}
    </section>
    <div className="mt-8 grid gap-8 xl:grid-cols-[1.3fr_.7fr]">
      <section className="panel" data-testid="dashboard-projects-panel"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="dashboard-projects-kicker">Canonical memory</p><h2 className="mt-1 font-heading text-3xl" data-testid="dashboard-projects-title">Project Holders</h2></div><Link to="/projects" className="text-xs text-muted-foreground hover:text-foreground" data-testid="dashboard-all-projects-link">View all →</Link></div><div className="divide-y divide-border">{(data?.projects ?? []).map((project) => <Link to={`/projects/${project.id}`} key={project.id} className="group block p-5 transition-[background-color] hover:bg-[#21191b]" data-testid={`dashboard-project-${project.id}-link`}><div className="flex items-start justify-between gap-5"><div><h3 className="font-heading text-2xl" data-testid={`dashboard-project-${project.id}-name`}>{project.name}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground" data-testid={`dashboard-project-${project.id}-description`}>{project.description}</p></div><StatusPill tone="brand">Rev {project.revision}</StatusPill></div><div className="mt-4 flex flex-wrap gap-2">{project.stack.slice(0, 4).map((item) => <span key={item} className="border border-border px-2 py-1 font-mono text-[9px] text-muted-foreground" data-testid={`dashboard-project-${project.id}-${item.toLowerCase().replaceAll(" ", "-")}-stack`}>{item}</span>)}</div></Link>)}</div></section>
      <section className="panel p-6" data-testid="dashboard-system-panel"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="dashboard-system-kicker">System status</p><StatusPill tone="good">Live</StatusPill></div><h2 className="mt-5 font-heading text-3xl" data-testid="dashboard-system-title">The context layer</h2><div className="mt-7 space-y-4">{Object.entries(data?.integration_status ?? {}).map(([key, value]) => <div className="border-b border-border pb-4" key={key} data-testid={`dashboard-integration-${key}`}><p className="text-xs capitalize text-muted-foreground" data-testid={`dashboard-integration-${key}-label`}>{key}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-wide" data-testid={`dashboard-integration-${key}-value`}>{value.replaceAll("_", " ")}</p></div>)}</div><div className="mt-8 bg-[#100d0e] p-4" data-testid="dashboard-mcp-endpoint"><p className="font-mono text-[9px] uppercase tracking-widest text-[#9f5169]" data-testid="dashboard-mcp-label">MCP endpoint</p><code className="mt-3 block break-all font-mono text-[10px] leading-5 text-muted-foreground" data-testid="dashboard-mcp-value">{data?.mcp_endpoint ?? "Loading endpoint…"}</code></div></section>
    </div></>}
  </AppShell>;
}