import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowUp, Braces, CheckCircle2, Route, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiGet, apiPost } from "@/lib/api";
import type { PlaygroundResponse, Project } from "@/lib/skipti";

export default function Playground() {
  const projects = useQuery({ queryKey: ["projects"], queryFn: () => apiGet<Project[]>("/projects"), retry: false });
  const [projectId, setProjectId] = useState("11111111-1111-4111-8111-111111111111"); const [query, setQuery] = useState("What should I work on next to validate cross-model project continuity?");
  const ask = useMutation({ mutationFn: () => apiPost<PlaygroundResponse>("/playground/ask", { query, project_id: projectId || null, max_entries: 7, session_id: "preview-playground" }), onError: () => toast.error("Gemini could not answer. Check the integration status and try again.") });
  const response = ask.data; const activeProject = projects.data?.find((project) => project.id === projectId);
  return <AppShell><PageHeader eyebrow="MCP playground" title="See exactly what the model receives." description="A real retrieval runs first. Only the selected approved context is sent to Gemini; the trace remains visible beside the response." action={<div className="flex gap-2"><StatusPill tone="good">Gemini</StatusPill><StatusPill tone="brand">MCP-ready</StatusPill></div>} />
    <section className="grid min-h-[680px] overflow-hidden rounded-2xl border border-border shadow-[0_24px_60px_rgba(0,0,0,.18)] xl:grid-cols-[1.08fr_.92fr]" data-testid="playground-workspace"><div className="flex flex-col bg-[#151313]" data-testid="playground-chat-panel"><div className="flex items-center justify-between border-b border-border p-5"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg border border-[#581d30] bg-[#1b0c10]"><Sparkles className="size-3.5 text-[#d7a0b1]" /></span><div><p className="text-xs font-medium" data-testid="playground-chat-title">Skipti-hosted Gemini</p><p className="font-mono text-[8px] uppercase tracking-widest text-muted-foreground" data-testid="playground-model-label">gemini-3-flash-preview</p></div></div><select className="max-w-52 rounded-lg border border-border bg-[#0c0a09] px-3 py-2 text-xs outline-none focus:border-[#872c4c]" value={projectId} onChange={(event) => setProjectId(event.target.value)} data-testid="playground-project-select"><option value="" label="Base Persona only" />{(projects.data ?? []).map((project) => <option key={project.id} value={project.id} label={`${project.name} · rev ${project.revision}`} />)}</select></div>
      <div className="flex-1 p-6 md:p-9" data-testid="playground-conversation"><div className="ml-auto max-w-[85%] border border-[#581d30] bg-[#1a0e12] p-4" data-testid="playground-user-message"><p className="font-mono text-[8px] uppercase tracking-widest text-[#c47a91]">You</p><p className="mt-2 text-sm leading-6" data-testid="playground-user-question">{response?.retrieval.query ?? query}</p></div>{ask.isPending ? <div className="mt-6 max-w-[85%] border border-border bg-[#100d0e] p-5" data-testid="playground-loading-response"><div className="flex items-center gap-3"><span className="size-1.5 animate-status-pulse rounded-full bg-[#c47a91]" /><p className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">Routing context, then asking Gemini…</p></div></div> : null}{response ? <div className="animate-trace-in mt-6 max-w-[92%] border border-border bg-[#100d0e] p-5" data-testid="playground-gemini-response"><div className="flex items-center gap-2"><Sparkles className="size-3.5 text-[#c47a91]" /><p className="font-mono text-[8px] uppercase tracking-widest text-[#c47a91]">Gemini with Skipti context</p></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#dedad7]" data-testid="playground-answer-text">{response.answer}</p></div> : <div className="mt-16 text-center" data-testid="playground-empty-state"><Braces className="mx-auto size-7 text-[#51494b]" /><p className="mt-4 font-heading text-3xl text-[#655d5a]" data-testid="playground-empty-title">The trace starts with your question.</p></div>}</div>
      <form className="border-t border-border p-5" onSubmit={(event) => { event.preventDefault(); ask.mutate(); }} data-testid="playground-question-form"><div className="relative"><Textarea className="min-h-24 pr-14" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask with your approved context…" required data-testid="playground-question-input" /><Button className="absolute bottom-3 right-3" size="icon" type="submit" disabled={ask.isPending || !query.trim()} aria-label="Ask Gemini" data-testid="playground-ask-button"><ArrowUp className="size-4" /></Button></div><p className="mt-2 font-mono text-[8px] uppercase tracking-widest text-muted-foreground" data-testid="playground-project-context-label">Context scope · {activeProject?.name ?? "Base Persona"}</p></form></div>
      <aside className="relative overflow-hidden border-t border-border bg-[#0e0c0c] xl:border-l xl:border-t-0" data-testid="playground-trace-panel"><div className="border-b border-border p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="playground-trace-kicker">Visible retrieval trace</p><h2 className="mt-1 font-heading text-3xl" data-testid="playground-trace-title">Context Router</h2></div><Route className="size-5 text-[#655d5a]" /></div></div>
      <div className="p-5" data-testid="playground-trace-content"><div className="grid grid-cols-3 gap-px bg-border" data-testid="playground-trace-stats">{[{ label: "Selected", value: response?.retrieval.selected.length ?? 0 }, { label: "Excluded", value: response?.retrieval.excluded_count ?? 0 }, { label: "Tokens", value: response ? `~${response.retrieval.approximate_tokens}` : "—" }].map((item) => <div className="bg-[#151313] p-4" key={item.label} data-testid={`playground-${item.label.toLowerCase()}-stat`}><p className="font-heading text-3xl" data-testid={`playground-${item.label.toLowerCase()}-value`}>{item.value}</p><p className="font-mono text-[8px] uppercase text-muted-foreground">{item.label}</p></div>)}</div>
      <div className="mt-7 space-y-0" data-testid="playground-flow-steps">{["Intent detection", "Authorization check", "Context search", "MCP tool request", "Gemini response"].map((step, index) => <div className="flex items-center gap-4 border-l border-border py-3 pl-4" key={step} data-testid={`playground-flow-step-${index}`}><CheckCircle2 className={`size-3.5 ${response || index < 2 ? "text-emerald-400" : "text-[#51494b]"}`} /><div><p className="font-mono text-[9px] text-[#dedad7]" data-testid={`playground-flow-step-${index}-name`}>{step}</p>{index === 3 ? <p className="mt-1 font-mono text-[8px] text-[#9f5169]" data-testid="playground-mcp-tool-name">tool: search_context</p> : null}</div></div>)}</div>
      <div className="mt-6" data-testid="playground-selected-context-list">{(response?.retrieval.selected ?? []).map((item, index) => <article className="animate-trace-in border-t border-border py-4" style={{ animationDelay: `${index * 80}ms` }} key={item.id} data-testid={`playground-context-${item.id}`}><div className="flex items-center justify-between gap-3"><p className="font-mono text-[9px] text-[#d7a0b1]" data-testid={`playground-context-${item.id}-label`}>{item.category} / {item.label}</p><span className="font-mono text-[8px] text-[#655d5a]" data-testid={`playground-context-${item.id}-source`}>{item.source}</span></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground" data-testid={`playground-context-${item.id}-value`}>{item.value}</p><p className="mt-2 font-mono text-[8px] text-[#655d5a]" data-testid={`playground-context-${item.id}-reason`}>↳ {item.reason}</p></article>)}</div></div></aside></section>
  </AppShell>;
}