import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clock3, GitBranch, History, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { toast } from "sonner";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { Button, buttonVariants } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiGet, apiPost } from "@/lib/api";
import type { ProgressProposal, ProjectCheckpoint, ProjectDetail as ProjectDetailType } from "@/lib/skipti";

function StateList({ title, items, tone, projectId }: { title: string; items: string[]; tone: string; projectId: string }) {
  return <section className="panel p-5" data-testid={`project-${projectId}-${title.toLowerCase().replaceAll(" ", "-")}-panel`}><div className="mb-5 flex items-center justify-between"><h3 className="font-heading text-2xl" data-testid={`project-${projectId}-${title.toLowerCase().replaceAll(" ", "-")}-title`}>{title}</h3><span className={`size-2 rounded-full ${tone}`} /></div>{items.length ? <ul className="space-y-3">{items.map((item, index) => <li className="border-l border-border pl-3 text-xs leading-5 text-muted-foreground" key={`${item}-${index}`} data-testid={`project-${projectId}-${title.toLowerCase().replaceAll(" ", "-")}-${index}-item`}>{item}</li>)}</ul> : <p className="text-xs text-muted-foreground" data-testid={`project-${projectId}-${title.toLowerCase().replaceAll(" ", "-")}-empty`}>No entries in the approved state.</p>}</section>;
}

export default function ProjectDetail() {
  const { id = "" } = useParams(); const client = useQueryClient(); const [update, setUpdate] = useState("");
  const detail = useQuery({ queryKey: ["project", id], queryFn: () => apiGet<ProjectDetailType>(`/projects/${id}`), enabled: Boolean(id) });
  const proposals = useQuery({ queryKey: ["project-proposals", id], queryFn: () => apiGet<ProgressProposal[]>(`/projects/${id}/proposals`), enabled: Boolean(id) });
  const project = detail.data?.project;
  const propose = useMutation({ mutationFn: () => apiPost<ProgressProposal>(`/projects/${id}/proposals`, { update_text: update, expected_revision: project?.revision, source_provider: "manual" }), onSuccess: () => { setUpdate(""); client.invalidateQueries({ queryKey: ["project-proposals", id] }); client.invalidateQueries({ queryKey: ["project", id] }); toast.success("Structured proposal ready for review"); }, onError: () => toast.error("Could not structure this update") });
  const approve = useMutation({ mutationFn: (proposalId: string) => apiPost<ProjectCheckpoint>(`/projects/${id}/proposals/${proposalId}/approve`, { expected_revision: project?.revision }), onSuccess: (checkpoint) => { client.invalidateQueries({ queryKey: ["project", id] }); client.invalidateQueries({ queryKey: ["project-proposals", id] }); client.invalidateQueries({ queryKey: ["project-history", id] }); toast.success(`Revision ${checkpoint.revision} saved`); }, onError: () => toast.error("Approval conflicted with a newer revision") });
  return <AppShell><PageHeader eyebrow="Project continuity" title={project?.name ?? "Loading Project Holder…"} description={project?.description ?? "Retrieving canonical state."} action={<div className="flex gap-2">{project ? <StatusPill tone="brand">Revision {project.revision}</StatusPill> : null}<Link to={`/projects/${id}/history`} className={buttonVariants({ variant: "outline", size: "sm" })} data-testid="project-history-link"><History className="size-4" /> History</Link></div>} />
    {project ? <><div className="mb-8 flex flex-wrap gap-2" data-testid="project-stack-list">{project.stack.map((item) => <span className="border border-border px-3 py-1.5 font-mono text-[9px] text-muted-foreground" key={item} data-testid={`project-stack-${item.toLowerCase().replaceAll(" ", "-")}`}>{item}</span>)}</div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" data-testid="project-state-grid"><StateList title="Completed" items={project.completed} tone="bg-emerald-400" projectId={project.id} /><StateList title="In progress" items={project.in_progress} tone="bg-amber-400" projectId={project.id} /><StateList title="Blockers" items={project.blockers} tone="bg-red-400" projectId={project.id} /><StateList title="Decisions" items={project.decisions} tone="bg-[#c47a91]" projectId={project.id} /><StateList title="Next steps" items={project.next_steps} tone="bg-sky-400" projectId={project.id} /></section>
      <section className="mt-8 grid gap-6 xl:grid-cols-[.82fr_1.18fr]" data-testid="project-update-workbench"><form className="panel p-6" onSubmit={(event) => { event.preventDefault(); propose.mutate(); }} data-testid="project-progress-form"><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="project-progress-kicker">AI-assisted checkpoint</p><h2 className="mt-3 font-heading text-3xl" data-testid="project-progress-title">Record meaningful progress.</h2><p className="mt-3 text-xs leading-5 text-muted-foreground" data-testid="project-progress-description">Describe what changed. Gemini structures it as reported work; nothing reaches canonical memory until you approve it.</p><Textarea className="mt-6 min-h-36" value={update} onChange={(event) => setUpdate(event.target.value)} placeholder="Finished the retrieval filter, decided to keep Streamable HTTP, and need to test remote discovery." required data-testid="project-progress-input" /><Button className="mt-4" type="submit" disabled={propose.isPending || !update.trim()} data-testid="project-progress-submit-button">{propose.isPending ? "Structuring update…" : "Create progress proposal"}<GitBranch className="size-4" /></Button></form>
      <div className="panel" data-testid="project-proposals-panel"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="project-proposals-kicker">Owner review queue</p><h2 className="mt-1 font-heading text-3xl" data-testid="project-proposals-title">Proposed updates</h2></div><StatusPill tone="warning">{detail.data?.pending_proposals ?? 0} pending</StatusPill></div><div className="divide-y divide-border">{(proposals.data ?? []).map((proposal) => <article className="p-5" key={proposal.id} data-testid={`project-proposal-${proposal.id}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Clock3 className="size-3.5 text-[#c47a91]" /><span className="font-mono text-[9px] uppercase text-muted-foreground" data-testid={`project-proposal-${proposal.id}-source`}>{proposal.source_provider} · base rev {proposal.base_revision}</span></div><h3 className="mt-3 text-sm font-medium" data-testid={`project-proposal-${proposal.id}-summary`}>{proposal.summary}</h3></div><StatusPill tone={proposal.status === "approved" ? "good" : "warning"}>{proposal.status.replaceAll("_", " ")}</StatusPill></div>{proposal.status === "pending_approval" ? <Button className="mt-5" size="sm" onClick={() => approve.mutate(proposal.id)} disabled={approve.isPending || proposal.base_revision !== project.revision} data-testid={`project-proposal-${proposal.id}-approve-button`}><ShieldCheck className="size-4" /> Approve as revision {project.revision + 1}</Button> : <div className="mt-4 flex items-center gap-2 text-xs text-emerald-300" data-testid={`project-proposal-${proposal.id}-approved-label`}><Check className="size-3.5" /> Canonical memory updated</div>}</article>)}{!proposals.data?.length ? <p className="p-6 text-sm text-muted-foreground" data-testid="project-proposals-empty">No proposals yet.</p> : null}</div></div></section>
    </> : null}
  </AppShell>;
}