import { useMutation } from "@tanstack/react-query";
import { Download, LogOut, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { apiGet, apiPost } from "@/lib/api";
import type { ExportResponse } from "@/lib/skipti";

export default function Settings() {
  const navigate = useNavigate();
  const exportPersona = useMutation({ mutationFn: () => apiGet<ExportResponse>("/persona/export"), onSuccess: (result) => { const blob = new Blob([result.markdown], { type: "text/markdown" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = result.filename; link.click(); URL.revokeObjectURL(url); toast.success(`Exported Persona revision ${result.revision}`); }, onError: () => toast.error("Could not export Persona context") });
  const logout = useMutation({ mutationFn: () => apiPost<{ message: string }>("/auth/logout"), onSuccess: () => navigate("/login") });
  return <AppShell><PageHeader eyebrow="Settings & privacy" title="Control the boundaries." description="Export approved context, inspect the active storage mode, and end the demo owner session." action={<StatusPill tone="warning">Preview environment</StatusPill>} />
    <section className="grid gap-6 lg:grid-cols-2" data-testid="settings-grid"><article className="panel p-7" data-testid="settings-export-card"><Download className="size-5 text-[#c47a91]" /><h2 className="mt-8 font-heading text-4xl" data-testid="settings-export-title">Context export</h2><p className="mt-3 text-sm leading-6 text-muted-foreground" data-testid="settings-export-description">Download a sanitized Markdown snapshot of approved, non-sensitive Base Persona entries. The database remains authoritative.</p><Button className="mt-7" onClick={() => exportPersona.mutate()} disabled={exportPersona.isPending} data-testid="settings-export-button"><Download className="size-4" />{exportPersona.isPending ? "Preparing export…" : "Download context.md"}</Button></article><article className="panel p-7" data-testid="settings-security-card"><ShieldCheck className="size-5 text-[#c47a91]" /><h2 className="mt-8 font-heading text-4xl" data-testid="settings-security-title">Environment</h2><div className="mt-5 divide-y divide-border">{[{ label: "Authentication", value: "Demo owner cookie" }, { label: "Storage", value: "Local Mongo adapter" }, { label: "Production target", value: "Supabase migration included" }, { label: "AI provider", value: "Gemini via managed key" }].map((row) => <div className="flex justify-between gap-4 py-3 text-xs" key={row.label} data-testid={`settings-${row.label.toLowerCase().replaceAll(" ", "-")}-row`}><span className="text-muted-foreground">{row.label}</span><span className="text-right" data-testid={`settings-${row.label.toLowerCase().replaceAll(" ", "-")}-value`}>{row.value}</span></div>)}</div></article><article className="panel border-red-950/60 p-7 lg:col-span-2" data-testid="settings-session-card"><LogOut className="size-5 text-red-400" /><h2 className="mt-6 font-heading text-3xl" data-testid="settings-session-title">End this owner session</h2><p className="mt-2 text-sm text-muted-foreground" data-testid="settings-session-description">This clears the current httpOnly demo session. Canonical demo data remains available for the next login.</p><Button className="mt-6" variant="destructive" onClick={() => logout.mutate()} disabled={logout.isPending} data-testid="settings-logout-button"><LogOut className="size-4" /> Sign out demo owner</Button></article></section>
  </AppShell>;
}