import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock3, Copy, QrCode, ShieldOff } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeader, StatusPill } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { apiGet, apiPost } from "@/lib/api";
import type { Project, ShareCreated, ShareGrant } from "@/lib/skipti";

const permissionOptions = [
  { id: "general_profile", label: "General profile", detail: "Approved non-sensitive Persona entries" },
  { id: "goals", label: "Goals", detail: "Current user-approved goals" },
  { id: "skills", label: "Skills", detail: "Relevant technical experience" },
  { id: "ai_preferences", label: "AI preferences", detail: "Response and collaboration style" },
  { id: "project", label: "Selected Project Holder", detail: "Overview and technical context" },
  { id: "project_progress", label: "Approved project progress", detail: "Latest canonical revision state" },
];

export default function Share() {
  const client = useQueryClient(); const [projectId, setProjectId] = useState("11111111-1111-4111-8111-111111111111"); const [duration, setDuration] = useState(15); const [permissions, setPermissions] = useState(new Set(["goals", "skills", "ai_preferences", "project", "project_progress"])); const [created, setCreated] = useState<ShareCreated | null>(null);
  const projects = useQuery({ queryKey: ["projects"], queryFn: () => apiGet<Project[]>("/projects") });
  const shares = useQuery({ queryKey: ["shares"], queryFn: () => apiGet<ShareGrant[]>("/shares"), retry: false });
  const create = useMutation({ mutationFn: () => apiPost<ShareCreated>("/shares", { project_id: projectId || null, permissions: [...permissions], duration_minutes: duration }), onSuccess: (grant) => { setCreated(grant); client.invalidateQueries({ queryKey: ["shares"] }); toast.success("One-time Persona Pass created"); }, onError: () => toast.error("Could not create the Persona Pass") });
  const revoke = useMutation({ mutationFn: (id: string) => apiPost<{ message: string }>(`/shares/${id}/revoke`), onSuccess: () => { setCreated(null); client.invalidateQueries({ queryKey: ["shares"] }); toast.success("Future guest retrieval blocked"); }, onError: () => toast.error("Could not revoke this pass") });
  return <AppShell><PageHeader eyebrow="Persona pass" title="Share less. For less time." description="Create a one-time QR credential with explicit permissions. The guest receives a separate read-only session that expires or can be revoked immediately." action={<StatusPill tone="brand">QR · Temporary · Read only</StatusPill>} />
    <section className="grid gap-7 xl:grid-cols-[.92fr_1.08fr]" data-testid="share-workspace"><form className="panel p-6 md:p-8" onSubmit={(event) => { event.preventDefault(); create.mutate(); }} data-testid="share-create-form"><p className="font-mono text-[9px] uppercase tracking-widest text-[#c47a91]" data-testid="share-form-kicker">Permission builder</p><h2 className="mt-2 font-heading text-4xl" data-testid="share-form-title">Create a Persona Pass</h2><div className="mt-7"><label className="mb-2 block text-xs text-muted-foreground" htmlFor="share-project" data-testid="share-project-label">Project scope</label><select id="share-project" className="w-full border border-border bg-[#0c0a09] px-3 py-3 text-sm outline-none focus:border-[#872c4c]" value={projectId} onChange={(event) => setProjectId(event.target.value)} data-testid="share-project-select"><option value="" label="No Project Holder" />{(projects.data ?? []).map((project) => <option key={project.id} value={project.id} label={`${project.name} · revision ${project.revision}`} />)}</select></div><div className="mt-7" data-testid="share-permissions-list"><p className="mb-3 text-xs text-muted-foreground" data-testid="share-permissions-label">Allowed context</p>{permissionOptions.map((permission) => <label className="flex cursor-pointer gap-3 border-t border-border py-4" key={permission.id} data-testid={`share-permission-${permission.id}-row`}><Checkbox checked={permissions.has(permission.id)} onCheckedChange={(checked) => setPermissions((current) => { const next = new Set(current); if (checked) next.add(permission.id); else next.delete(permission.id); return next; })} data-testid={`share-permission-${permission.id}-checkbox`} /><div><p className="text-sm" data-testid={`share-permission-${permission.id}-label`}>{permission.label}</p><p className="mt-1 text-[11px] text-muted-foreground" data-testid={`share-permission-${permission.id}-detail`}>{permission.detail}</p></div></label>)}</div><div className="mt-6"><p className="mb-3 text-xs text-muted-foreground" data-testid="share-duration-label">Access duration</p><div className="grid grid-cols-4 gap-2" data-testid="share-duration-options">{[5, 15, 30, 60].map((minutes) => <button type="button" key={minutes} onClick={() => setDuration(minutes)} className={`border px-3 py-3 font-mono text-[9px] transition-[border-color,background-color] ${duration === minutes ? "border-[#872c4c] bg-[#1b0c10] text-[#e0a7b8]" : "border-border text-muted-foreground hover:border-[#581d30]"}`} data-testid={`share-duration-${minutes}-button`}>{minutes === 60 ? "1 hour" : `${minutes} min`}</button>)}</div></div><Button className="mt-7 w-full" size="lg" type="submit" disabled={create.isPending || permissions.size === 0} data-testid="share-generate-button"><QrCode className="size-4" />{create.isPending ? "Generating secure pass…" : "Generate one-time QR"}</Button></form>
      <div className="space-y-7" data-testid="share-preview-column"><section className="relative min-h-[520px] overflow-hidden border border-[#581d30] bg-[url('https://images.unsplash.com/photo-1629197520669-0210d6b270d9?auto=format&fit=crop&w=1200&q=80')] bg-cover bg-center p-6 md:p-9" data-testid="share-pass-preview"><div className="absolute inset-0 bg-[#160b0e]/86 backdrop-blur-sm" /><div className="relative z-10 flex min-h-[450px] flex-col"><div className="flex items-start justify-between"><div><p className="font-heading text-3xl" data-testid="share-preview-brand">Skipti Persona Pass</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[.2em] text-[#d7a0b1]" data-testid="share-preview-caption">Temporary context handoff</p></div><StatusPill tone={created ? "good" : "neutral"}>{created ? "Ready" : "Draft"}</StatusPill></div>{created ? <div className="my-auto grid items-center gap-7 md:grid-cols-[220px_1fr]" data-testid="share-created-pass"><div className="bg-[#fafaf9] p-4"><img src={created.qr_data_uri} alt="One-time Skipti Persona Pass QR code" className="w-full" data-testid="share-qr-image" /></div><div><p className="font-mono text-[9px] uppercase tracking-widest text-[#d7a0b1]" data-testid="share-created-duration">Expires {new Date(created.expires_at).toLocaleTimeString()}</p><h3 className="mt-3 font-heading text-4xl" data-testid="share-created-title">Scan once.<br />Continue with context.</h3><p className="mt-4 text-xs leading-5 text-[#c5b8bc]" data-testid="share-created-description">The QR contains no Persona data. Redemption exchanges its one-time credential for a scoped guest session.</p><div className="mt-5 flex gap-2"><Button size="sm" variant="outline" type="button" onClick={() => { navigator.clipboard.writeText(created.connect_url); toast.success("Secure link copied"); }} data-testid="share-copy-link-button"><Copy className="size-3.5" /> Copy link</Button><Button size="sm" variant="destructive" type="button" onClick={() => revoke.mutate(created.id)} data-testid="share-created-revoke-button"><ShieldOff className="size-3.5" /> Revoke</Button></div></div></div> : <div className="my-auto text-center" data-testid="share-empty-preview"><QrCode className="mx-auto size-16 text-[#6b3949]" /><h3 className="mt-6 font-heading text-4xl text-[#d4bcc4]" data-testid="share-empty-title">Your temporary pass appears here.</h3><p className="mx-auto mt-3 max-w-md text-xs leading-5 text-[#9e8790]" data-testid="share-empty-description">Select only the context needed on the other device.</p></div>}<div className="mt-auto flex items-center gap-2 border-t border-[#6e3346] pt-4 text-[10px] text-[#c5b8bc]" data-testid="share-revocation-note"><Clock3 className="size-3.5" /> Revocation blocks future Skipti retrieval; it cannot erase information already viewed or copied.</div></div></section>
      <section className="panel" data-testid="share-active-sessions"><div className="border-b border-border p-5"><h2 className="font-heading text-3xl" data-testid="share-active-title">Recent passes</h2></div><div className="divide-y divide-border">{(shares.data ?? []).slice(0, 4).map((share) => <div className="flex items-center justify-between gap-4 p-4" key={share.id} data-testid={`share-session-${share.id}`}><div><p className="font-mono text-[9px] uppercase text-muted-foreground" data-testid={`share-session-${share.id}-id`}>{share.id.slice(0, 8)}</p><p className="mt-1 text-xs text-muted-foreground" data-testid={`share-session-${share.id}-expiry`}>Until {new Date(share.expires_at).toLocaleTimeString()}</p></div><div className="flex items-center gap-2"><StatusPill tone={share.status === "active" || share.status === "ready" ? "good" : "neutral"}>{share.status}</StatusPill>{share.status !== "revoked" ? <Button variant="ghost" size="sm" onClick={() => revoke.mutate(share.id)} data-testid={`share-session-${share.id}-revoke-button`}>Revoke</Button> : null}</div></div>)}</div></section></div></section>
  </AppShell>;
}